Standard Permissions:
  View Profile:
    type: user
    controller_area:
      -
        controller: profile
        action_names: show
    model_area:
      -
        model: profile
        check_method: check_user_privacy_setting

Roles:
  Manage Roles:
    type: admin
    controller_area:
      -
        controller: roles
        action_names: all
    model_area:
      -
        model: role
Users:
  Create Admin Users:
    type: admin
    controller_area:
      -
        controller: users
        action_names: new, create
    model_area:
      -
        model: user
  Watch Users:
    type: admin
    controller_area:
      -
        controller: users
        action_names: index, show
    model_area:
      -
        model: user
  Add Standard Role to User:
    type: admin
    controller_area:
      -
        controller: users
        action_names: add_role_to_user
    model_area:
      -
        model: user
  Add Any Role to User:
    type: admin
    controller_area:
      -
        controller: users
        action_names: add_role_to_user
    model_area:
      -
        model: user
  Activate/Deactivate Users:
    type: admin
    controller_area:
      -
        controller: users
        action_names: toggle_user_active_status
    model_area:
      -
        model: user