login: &login
  adapter: mysql2
  host: localhost
  username: root
  password: rem

development: &development
  database: tb_dev
  <<: *login

test: &test
  database: test_m3
  <<: *login

production: &production
  adapter: mysql2
  host: localhost
  database: prod_m3
  username: root
  password:
